/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'diwaliLakshmiGanesh' : IDL.Null,
  'radhaKrishna' : IDL.Null,
  'lakshmi' : IDL.Null,
  'vishwakarma' : IDL.Null,
  'custom' : IDL.Null,
  'saraswati' : IDL.Null,
  'kali' : IDL.Null,
  'ganesh' : IDL.Null,
  'banglaLakshmiGanesh' : IDL.Null,
  'durga' : IDL.Null,
  'kartik' : IDL.Null,
});
export const AddProductInput = IDL.Record({
  'nameBn' : IDL.Text,
  'nameEn' : IDL.Text,
  'descriptionBn' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'imageIds' : IDL.Vec(IDL.Text),
  'bulkAvailable' : IDL.Bool,
  'category' : ProductCategory,
  'priceRangeMax' : IDL.Nat,
  'priceRangeMin' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'nameBn' : IDL.Text,
  'nameEn' : IDL.Text,
  'descriptionBn' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'createdAt' : IDL.Int,
  'sizes' : IDL.Vec(IDL.Text),
  'updatedAt' : IDL.Int,
  'imageIds' : IDL.Vec(IDL.Text),
  'bulkAvailable' : IDL.Bool,
  'category' : ProductCategory,
  'priceRangeMax' : IDL.Nat,
  'priceRangeMin' : IDL.Nat,
});
export const BannerImage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'imageUrl' : IDL.Text,
});
export const CategoryImage = IDL.Record({
  'slug' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const CategoryInfo = IDL.Record({
  'nameBn' : IDL.Text,
  'nameEn' : IDL.Text,
  'slug' : IDL.Text,
});
export const InquiryRecord = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'productInterest' : IDL.Text,
  'phone' : IDL.Text,
});
export const VisitorProfile = IDL.Record({
  'principal' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const UpdateProductInput = IDL.Record({
  'id' : IDL.Nat,
  'nameBn' : IDL.Text,
  'nameEn' : IDL.Text,
  'descriptionBn' : IDL.Text,
  'descriptionEn' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'imageIds' : IDL.Vec(IDL.Text),
  'bulkAvailable' : IDL.Bool,
  'category' : ProductCategory,
  'priceRangeMax' : IDL.Nat,
  'priceRangeMin' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [AddProductInput, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
      [],
    ),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'deleteFile' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteProduct' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getBannerImages' : IDL.Func([], [IDL.Vec(BannerImage)], ['query']),
  'getCategoryImage' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getCategoryImages' : IDL.Func([], [IDL.Vec(CategoryImage)], ['query']),
  'getCategoryList' : IDL.Func([], [IDL.Vec(CategoryInfo)], ['query']),
  'getFeaturedProductIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getFileUrl' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getInquiries' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Vec(InquiryRecord), 'err' : IDL.Text })],
      [],
    ),
  'getMyProfile' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : VisitorProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'getOwnerPrincipal' : IDL.Func([], [IDL.Text], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUploadUrl' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'uploadUrl' : IDL.Text, 'fileId' : IDL.Text }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'getVisitors' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Vec(VisitorProfile), 'err' : IDL.Text })],
      [],
    ),
  'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
  'registerVisitor' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : VisitorProfile, 'err' : IDL.Text })],
      [],
    ),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateBannerImages' : IDL.Func(
      [IDL.Vec(BannerImage), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCategoryImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateFeaturedProductIds' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateProduct' : IDL.Func(
      [UpdateProductInput, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
      [],
    ),
  'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'diwaliLakshmiGanesh' : IDL.Null,
    'radhaKrishna' : IDL.Null,
    'lakshmi' : IDL.Null,
    'vishwakarma' : IDL.Null,
    'custom' : IDL.Null,
    'saraswati' : IDL.Null,
    'kali' : IDL.Null,
    'ganesh' : IDL.Null,
    'banglaLakshmiGanesh' : IDL.Null,
    'durga' : IDL.Null,
    'kartik' : IDL.Null,
  });
  const AddProductInput = IDL.Record({
    'nameBn' : IDL.Text,
    'nameEn' : IDL.Text,
    'descriptionBn' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'imageIds' : IDL.Vec(IDL.Text),
    'bulkAvailable' : IDL.Bool,
    'category' : ProductCategory,
    'priceRangeMax' : IDL.Nat,
    'priceRangeMin' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'nameBn' : IDL.Text,
    'nameEn' : IDL.Text,
    'descriptionBn' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'createdAt' : IDL.Int,
    'sizes' : IDL.Vec(IDL.Text),
    'updatedAt' : IDL.Int,
    'imageIds' : IDL.Vec(IDL.Text),
    'bulkAvailable' : IDL.Bool,
    'category' : ProductCategory,
    'priceRangeMax' : IDL.Nat,
    'priceRangeMin' : IDL.Nat,
  });
  const BannerImage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'imageUrl' : IDL.Text,
  });
  const CategoryImage = IDL.Record({
    'slug' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const CategoryInfo = IDL.Record({
    'nameBn' : IDL.Text,
    'nameEn' : IDL.Text,
    'slug' : IDL.Text,
  });
  const InquiryRecord = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'productInterest' : IDL.Text,
    'phone' : IDL.Text,
  });
  const VisitorProfile = IDL.Record({
    'principal' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const UpdateProductInput = IDL.Record({
    'id' : IDL.Nat,
    'nameBn' : IDL.Text,
    'nameEn' : IDL.Text,
    'descriptionBn' : IDL.Text,
    'descriptionEn' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'imageIds' : IDL.Vec(IDL.Text),
    'bulkAvailable' : IDL.Bool,
    'category' : ProductCategory,
    'priceRangeMax' : IDL.Nat,
    'priceRangeMin' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [AddProductInput, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
        [],
      ),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'deleteFile' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteProduct' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getBannerImages' : IDL.Func([], [IDL.Vec(BannerImage)], ['query']),
    'getCategoryImage' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getCategoryImages' : IDL.Func([], [IDL.Vec(CategoryImage)], ['query']),
    'getCategoryList' : IDL.Func([], [IDL.Vec(CategoryInfo)], ['query']),
    'getFeaturedProductIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getFileUrl' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getInquiries' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Vec(InquiryRecord), 'err' : IDL.Text })],
        [],
      ),
    'getMyProfile' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : VisitorProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'getOwnerPrincipal' : IDL.Func([], [IDL.Text], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUploadUrl' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'uploadUrl' : IDL.Text, 'fileId' : IDL.Text }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getVisitors' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Vec(VisitorProfile), 'err' : IDL.Text })],
        [],
      ),
    'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
    'registerVisitor' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : VisitorProfile, 'err' : IDL.Text })],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateBannerImages' : IDL.Func(
        [IDL.Vec(BannerImage), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCategoryImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateFeaturedProductIds' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateProduct' : IDL.Func(
        [UpdateProductInput, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
        [],
      ),
    'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };