/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddProductInput {
  'nameBn' : string,
  'nameEn' : string,
  'descriptionBn' : string,
  'descriptionEn' : string,
  'sizes' : Array<string>,
  'imageIds' : Array<string>,
  'bulkAvailable' : boolean,
  'category' : ProductCategory,
  'priceRangeMax' : bigint,
  'priceRangeMin' : bigint,
}
export interface BannerImage {
  'id' : string,
  'title' : string,
  'displayOrder' : bigint,
  'imageUrl' : string,
}
export interface CategoryImage { 'slug' : string, 'imageUrl' : string }
export interface CategoryInfo {
  'nameBn' : string,
  'nameEn' : string,
  'slug' : string,
}
export interface InquiryRecord {
  'id' : bigint,
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
  'productInterest' : string,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'nameBn' : string,
  'nameEn' : string,
  'descriptionBn' : string,
  'descriptionEn' : string,
  'createdAt' : bigint,
  'sizes' : Array<string>,
  'updatedAt' : bigint,
  'imageIds' : Array<string>,
  'bulkAvailable' : boolean,
  'category' : ProductCategory,
  'priceRangeMax' : bigint,
  'priceRangeMin' : bigint,
}
export type ProductCategory = { 'diwaliLakshmiGanesh' : null } |
  { 'radhaKrishna' : null } |
  { 'lakshmi' : null } |
  { 'vishwakarma' : null } |
  { 'custom' : null } |
  { 'saraswati' : null } |
  { 'kali' : null } |
  { 'ganesh' : null } |
  { 'banglaLakshmiGanesh' : null } |
  { 'durga' : null } |
  { 'kartik' : null };
export interface UpdateProductInput {
  'id' : bigint,
  'nameBn' : string,
  'nameEn' : string,
  'descriptionBn' : string,
  'descriptionEn' : string,
  'sizes' : Array<string>,
  'imageIds' : Array<string>,
  'bulkAvailable' : boolean,
  'category' : ProductCategory,
  'priceRangeMax' : bigint,
  'priceRangeMin' : bigint,
}
export interface VisitorProfile {
  'principal' : string,
  'name' : string,
  'phone' : string,
  'registeredAt' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [AddProductInput, [] | [string]],
    { 'ok' : Product } |
      { 'err' : string }
  >,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminLogout' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<
    [bigint, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getBannerImages' : ActorMethod<[], Array<BannerImage>>,
  'getCategoryImage' : ActorMethod<[string], [] | [string]>,
  'getCategoryImages' : ActorMethod<[], Array<CategoryImage>>,
  'getCategoryList' : ActorMethod<[], Array<CategoryInfo>>,
  'getFeaturedProductIds' : ActorMethod<[], Array<bigint>>,
  'getInquiries' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<InquiryRecord> } |
      { 'err' : string }
  >,
  'getMyProfile' : ActorMethod<
    [],
    { 'ok' : VisitorProfile } |
      { 'err' : string }
  >,
  'getOwnerPrincipal' : ActorMethod<[], string>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getVisitors' : ActorMethod<
    [[] | [string]],
    { 'ok' : Array<VisitorProfile> } |
      { 'err' : string }
  >,
  'isAdminCaller' : ActorMethod<[], boolean>,
  'registerVisitor' : ActorMethod<
    [string, string],
    { 'ok' : VisitorProfile } |
      { 'err' : string }
  >,
  'submitInquiry' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateBannerImages' : ActorMethod<
    [Array<BannerImage>, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCategoryImage' : ActorMethod<[string, string, [] | [string]], boolean>,
  'updateFeaturedProductIds' : ActorMethod<
    [Array<bigint>, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProduct' : ActorMethod<
    [UpdateProductInput, [] | [string]],
    { 'ok' : Product } |
      { 'err' : string }
  >,
  'validateAdminSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];