/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VisitorProfile {
    principal: string;
    name: string;
    phone: string;
    registeredAt: bigint;
}
export interface AddProductInput {
    nameBn: string;
    nameEn: string;
    descriptionBn: string;
    descriptionEn: string;
    sizes: Array<string>;
    imageIds: Array<string>;
    bulkAvailable: boolean;
    category: ProductCategory;
    priceRangeMax: bigint;
    priceRangeMin: bigint;
}
export interface CategoryImage {
    slug: string;
    imageUrl: string;
}
export interface InquiryRecord {
    id: bigint;
    name: string;
    message: string;
    timestamp: bigint;
    productInterest: string;
    phone: string;
}
export interface Product {
    id: bigint;
    nameBn: string;
    nameEn: string;
    descriptionBn: string;
    descriptionEn: string;
    createdAt: bigint;
    sizes: Array<string>;
    updatedAt: bigint;
    imageIds: Array<string>;
    bulkAvailable: boolean;
    category: ProductCategory;
    priceRangeMax: bigint;
    priceRangeMin: bigint;
}
export interface UpdateProductInput {
    id: bigint;
    nameBn: string;
    nameEn: string;
    descriptionBn: string;
    descriptionEn: string;
    sizes: Array<string>;
    imageIds: Array<string>;
    bulkAvailable: boolean;
    category: ProductCategory;
    priceRangeMax: bigint;
    priceRangeMin: bigint;
}
export enum ProductCategory {
    lakshmi = "lakshmi",
    custom = "custom",
    saraswati = "saraswati",
    hanuman = "hanuman",
    ganesh = "ganesh",
    durga = "durga"
}
export interface backendInterface {
    addProduct(input: AddProductInput): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteProduct(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCategoryImage(slug: string): Promise<string | null>;
    getCategoryImages(): Promise<Array<CategoryImage>>;
    getInquiries(): Promise<{
        __kind__: "ok";
        ok: Array<InquiryRecord>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyProfile(): Promise<{
        __kind__: "ok";
        ok: VisitorProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getOwnerPrincipal(): Promise<string>;
    getProduct(id: bigint): Promise<Product | null>;
    getProducts(): Promise<Array<Product>>;
    getVisitors(): Promise<{
        __kind__: "ok";
        ok: Array<VisitorProfile>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    isAdminCaller(): Promise<boolean>;
    registerVisitor(name: string, phone: string): Promise<{
        __kind__: "ok";
        ok: VisitorProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitInquiry(name: string, phone: string, productInterest: string, message: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateCategoryImage(slug: string, imageUrl: string): Promise<boolean>;
    updateProduct(input: UpdateProductInput): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AddProductInput as _AddProductInput, InquiryRecord as _InquiryRecord, Product as _Product, ProductCategory as _ProductCategory, UpdateProductInput as _UpdateProductInput, VisitorProfile as _VisitorProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: AddProductInput): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_AddProductInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_AddProductInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryImage(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryImage(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryImage(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryImages(): Promise<Array<CategoryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryImages();
            return result;
        }
    }
    async getInquiries(): Promise<{
        __kind__: "ok";
        ok: Array<InquiryRecord>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiries();
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiries();
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<{
        __kind__: "ok";
        ok: VisitorProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnerPrincipal(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerPrincipal();
            return result;
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitors(): Promise<{
        __kind__: "ok";
        ok: Array<VisitorProfile>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitors();
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitors();
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminCaller(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminCaller();
            return result;
        }
    }
    async registerVisitor(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: VisitorProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVisitor(arg0, arg1);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVisitor(arg0, arg1);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCategoryImage(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategoryImage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategoryImage(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: UpdateProductInput): Promise<{
        __kind__: "ok";
        ok: Product;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(to_candid_UpdateProductInput_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(to_candid_UpdateProductInput_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ProductCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    nameBn: string;
    nameEn: string;
    descriptionBn: string;
    descriptionEn: string;
    createdAt: bigint;
    sizes: Array<string>;
    updatedAt: bigint;
    imageIds: Array<string>;
    bulkAvailable: boolean;
    category: _ProductCategory;
    priceRangeMax: bigint;
    priceRangeMin: bigint;
}): {
    id: bigint;
    nameBn: string;
    nameEn: string;
    descriptionBn: string;
    descriptionEn: string;
    createdAt: bigint;
    sizes: Array<string>;
    updatedAt: bigint;
    imageIds: Array<string>;
    bulkAvailable: boolean;
    category: ProductCategory;
    priceRangeMax: bigint;
    priceRangeMin: bigint;
} {
    return {
        id: value.id,
        nameBn: value.nameBn,
        nameEn: value.nameEn,
        descriptionBn: value.descriptionBn,
        descriptionEn: value.descriptionEn,
        createdAt: value.createdAt,
        sizes: value.sizes,
        updatedAt: value.updatedAt,
        imageIds: value.imageIds,
        bulkAvailable: value.bulkAvailable,
        category: from_candid_ProductCategory_n8(_uploadFile, _downloadFile, value.category),
        priceRangeMax: value.priceRangeMax,
        priceRangeMin: value.priceRangeMin
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_InquiryRecord>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<InquiryRecord>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _VisitorProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: VisitorProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_VisitorProfile>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<VisitorProfile>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Product;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Product;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Product_n6(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lakshmi: null;
} | {
    custom: null;
} | {
    saraswati: null;
} | {
    hanuman: null;
} | {
    ganesh: null;
} | {
    durga: null;
}): ProductCategory {
    return "lakshmi" in value ? ProductCategory.lakshmi : "custom" in value ? ProductCategory.custom : "saraswati" in value ? ProductCategory.saraswati : "hanuman" in value ? ProductCategory.hanuman : "ganesh" in value ? ProductCategory.ganesh : "durga" in value ? ProductCategory.durga : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n6(_uploadFile, _downloadFile, x));
}
function to_candid_AddProductInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddProductInput): _AddProductInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProductInput_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProductInput): _UpdateProductInput {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    nameBn: string;
    nameEn: string;
    descriptionBn: string;
    descriptionEn: string;
    sizes: Array<string>;
    imageIds: Array<string>;
    bulkAvailable: boolean;
    category: ProductCategory;
    priceRangeMax: bigint;
    priceRangeMin: bigint;
}): {
    id: bigint;
    nameBn: string;
    nameEn: string;
    descriptionBn: string;
    descriptionEn: string;
    sizes: Array<string>;
    imageIds: Array<string>;
    bulkAvailable: boolean;
    category: _ProductCategory;
    priceRangeMax: bigint;
    priceRangeMin: bigint;
} {
    return {
        id: value.id,
        nameBn: value.nameBn,
        nameEn: value.nameEn,
        descriptionBn: value.descriptionBn,
        descriptionEn: value.descriptionEn,
        sizes: value.sizes,
        imageIds: value.imageIds,
        bulkAvailable: value.bulkAvailable,
        category: to_candid_ProductCategory_n3(_uploadFile, _downloadFile, value.category),
        priceRangeMax: value.priceRangeMax,
        priceRangeMin: value.priceRangeMin
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nameBn: string;
    nameEn: string;
    descriptionBn: string;
    descriptionEn: string;
    sizes: Array<string>;
    imageIds: Array<string>;
    bulkAvailable: boolean;
    category: ProductCategory;
    priceRangeMax: bigint;
    priceRangeMin: bigint;
}): {
    nameBn: string;
    nameEn: string;
    descriptionBn: string;
    descriptionEn: string;
    sizes: Array<string>;
    imageIds: Array<string>;
    bulkAvailable: boolean;
    category: _ProductCategory;
    priceRangeMax: bigint;
    priceRangeMin: bigint;
} {
    return {
        nameBn: value.nameBn,
        nameEn: value.nameEn,
        descriptionBn: value.descriptionBn,
        descriptionEn: value.descriptionEn,
        sizes: value.sizes,
        imageIds: value.imageIds,
        bulkAvailable: value.bulkAvailable,
        category: to_candid_ProductCategory_n3(_uploadFile, _downloadFile, value.category),
        priceRangeMax: value.priceRangeMax,
        priceRangeMin: value.priceRangeMin
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    lakshmi: null;
} | {
    custom: null;
} | {
    saraswati: null;
} | {
    hanuman: null;
} | {
    ganesh: null;
} | {
    durga: null;
} {
    return value == ProductCategory.lakshmi ? {
        lakshmi: null
    } : value == ProductCategory.custom ? {
        custom: null
    } : value == ProductCategory.saraswati ? {
        saraswati: null
    } : value == ProductCategory.hanuman ? {
        hanuman: null
    } : value == ProductCategory.ganesh ? {
        ganesh: null
    } : value == ProductCategory.durga ? {
        durga: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
